name: Compilare One UI 8
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descarcă proiectul tău
        uses: actions/checkout@v4

      - name: Descarcă baza de Android (Link Reparat)
        run: |
          # Descarcă o bază stabilă de LineageOS 21 AOSP direct de pe serverele de mirror
          wget -O system.img.xz "https://sourceforge.net"
          
          # Dezarhivează fișierul
          xz -d system.img.xz
          
          # Verifică dacă fișierul system.img s-a generat corect
          ls -l system.img

      - name: Execută transformarea One UI
        run: |
          chmod +x build_unified.sh
          ./build_unified.sh

      - name: Salvează GSI-ul tău modificat
        uses: actions/upload-artifact@v4
        with:
          name: OneUI-8-Redmi9T
          path: system.img
